# Generated by Django 4.1.5 on 2023-01-25 14:49

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=embed_video.fields.EmbedVideoField(blank=True, max_length=140, null=True),
        ),
    ]
